services:
  sqlapify:
    container_name: sqlapify
    build:
      context: .
      args:
        - BUILD_TARGET=postgres
      dockerfile: Dockerfile.dev    
    ports:
      - "8000:8000"
    env_file:
      - ./env/.env.$BUILD_TARGET.dev
    environment:
      PYTHONPATH: /app/venv/src
    volumes:
      - ./src:/app/venv/src
    