ARG ALPINE_VERSION=latest
ARG WORKDIR_APP=/app

ARG BUID_DEPS=sqlite-libs 

FROM yidoughi/pythopine:${ALPINE_VERSION} AS builder

ARG WORKDIR_APP

ARG VIRTUAL_ENV=${WORKDIR_APP}/venv

ARG BUID_DEPS
ARG BUILD_TARGET=postgres
ARG APP_ENV=dev

ARG MAIN_REQUIREMENT_FILE=requirements.${BUILD_TARGET}.txt

ARG DEPS_FILE_PATH=requirement/${APP_ENV}/${MAIN_REQUIREMENT_FILE}

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR ${VIRTUAL_ENV}

COPY --chown=1001:1001 requirements.txt  ${DEPS_FILE_PATH} ${VIRTUAL_ENV}

RUN mkdir ${VIRTUAL_ENV}/src && pip --no-cache-dir install -r requirements.txt -r ${MAIN_REQUIREMENT_FILE}

COPY --chown=1001:1001 env ${VIRTUAL_ENV}/env
COPY --chown=1001:1001  src ${VIRTUAL_ENV}/src

RUN rm requirements.txt -r ${MAIN_REQUIREMENT_FILE}  



FROM yidoughi/fastpine:latest

ARG WORKDIR_APP=/app
ARG VIRTUAL_ENV=${WORKDIR_APP}/venv

ENV HOME=${VIRTUAL_ENV}

ENV PATH="$VIRTUAL_ENV/bin:$PATH"

WORKDIR ${HOME}

RUN ls -la /usr/lib

COPY --from=builder --chown=1001 ${VIRTUAL_ENV} ${VIRTUAL_ENV} 


RUN rm -rf /var/cache/apk/* /tmp/* && fastapi --help


# CMD ["fastapi", "run", "src/main.py", "--host 0.0.0.0"]

# CMD ["tail", "-f", "/dev/null"]

CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload"]