[metadata]
name = "SQLApify"
version = "1.0.0"
description = "Talk with a DBMS throug a REST API"
author = "Yani IDOUGHI"
author_email = "idoughiyani@gmail.com"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "--disable-warnings"
pythonpath = ["src"]